### ISSUE TITLE
Cannot change collection name on the user model

### ISSUE THREAD

**Issue by MrBoolean** [strongloop/loopback-connector-mongodb#152]
Hi Guys,

as you can see i extend the `User` model by defining `BaseUser` as follows:

```javascript
{
  "name": "BaseUser",
  "mongodb": {
    "collection": "user"
  },
  "plural": "user",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "firstname": {
      "type": "string"
    },
    "lastname": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": []
}
```

Unfortunately, if I create a new `user` the collection is called `User` insteadof `user` (first character should be lowercased).

Don't know why.

Greets,
Marc

**Comment by superkhau** [comment]
LoopBack is doing the proper thing by naming your mongodb collection `user` (since you set the collection property in the definition).

1. If the `collection` property is specified in the model definition (ie. `common/models/model.json`), it will use what you define as the collection name.
2. If there is no collection property set in the definition, it will use the model name (ie. `BaseUser` in your case).

I've tested out what you propose and everything is working properly. See https://github.com/superkhau/sandbox/tree/bug/lb-con-mongodb152

Closing. Re-open if you still believe there are issues.

For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
