### ISSUE TITLE
How do you do an $elemMatch style query in loopback?

### ISSUE THREAD

**Issue by jamesjjk** [strongloop/loopback-connector-mongodb#168]
For example:

db.myCollection.find( { active: true, $where: "this.credits - this.debits < 0" } );

Or

db.myCollection.update( { active: true, $where: "this.credits - this.debits < 0" },{SOME UPDATE} );

I have switched on .dataSource.settings.allowExtendedOperators = true;

**Comment by ainesophaur** [comment]
I just worked with it last night and got it to work this way

```javascript
BoomReservation.find({
            where: {
                boomCustomerId: user,
                status: 'Purchased',
                boomReservationOffers: {
                    elemMatch: {
                        boomOfferId: self._id
                    }
                }
            },
            order: 'redeemedAt DESC'
        }, function(err, lastReservations) {});
```

**Comment by jamesjjk** [comment]
@ainesophaur Thanks for the reply. But where did you define self? And how would you use the operators?

**Comment by ainesophaur** [comment]
@jamesjjk that call is from a instance method for another model called BoomOffer -- so self references the instance of BoomOffer.prototype.this

As far as I can tell any of the default mongo operators like $gt, $in, $elemMatch are available in loopback, just call them without the $ -- which specific operators are we talking about though?

I dont think you need $elemMatch though  .. see if this gets you any closer -- if not I'll create a collection on my end and test  more thoroughly 

```javascript
{
  where : {
    $and : [
     {  active : true },  
     { gt : [subtract : ["$credits", "$debits"], 0]}
    ]
   }
}
```

**Comment by jamesjjk** [comment]
@ainesophaur You are right I don't need an element match but good to see it works. I have tried permutations of the above. I'm trying to update a 'stock' value with a specific ID where its 'credits' - 'debits' are less then < 0 for the document in question. I can do this in Mongodb, however trying to find documentation on how to use the loopback model.execute command is not easy... But I would rather do it in loopback.. any ideas?

**Comment by ainesophaur** [comment]
@jamesjjk I've been racking my brain on it for the past hour and I cannot see any way that you can do it directly through the strongloop models. You'll probably have to do a raw mongodb query and then init the models from the results. 

Mongo lets us do something like this: 
`db.getCollection('Stock').find( {$where : function(){return (this.credits -  this.debits < 0)} })` 

It would be nice if the connector would allow us to pass in a function for the filter/query like we can in mongo. I understand they're trying to be agnostic as possible but there are features and reasons people choose mongodb for over other data store types.. 

Currently we can only interact with basic filters such as where, fields, sort, include and skip.. in order to do things like $subtract we have to do it in a $project which we dont have access to through the mongodb connector.

**Comment by jamesjjk** [comment]
@ainesophaur Thanks! I has a feeling the loopback connector would not be able to do something like this. It makes fairly simple atomic operations very complicated to achieve. Like the above where we simply want to compare values, prior to an insert. This is used in many transactions. There is an execute method but its not documented properly and hopefully the LB team can feedback on this one..

**Comment by jamesjjk** [comment]
@ainesophaur Just an FYI you require to wrap function when using the mongodb node driver.

**Comment by anagrath** [comment]
I am having issues with an elemMatch on a referencesMany relationship where we are just storing the objectId of the referenced object....

**Comment by bugdanov** [comment]
I had a similar case. I believe the former works when categoryId is a String and the latter works when it is an ObjectId.
