### ISSUE TITLE
Documentation - datasources.json

### ISSUE THREAD

**Issue by benkroeger** [strongloop/loopback-connector-mongodb#200]
Just found out, that if you provide a `url` property in your `datasources.json` file, other properties like `hostname`, `port`, `username`, `password`, `database` are ignored.  
I actually wanted to override my general `datasources.json` with an environment specific `datasources.production.json` - had `url` defined in the global one but wanted to use all other properties in the environment file.  
Setting `url` to `false` in the environment file solved the problem

**Comment by crandmck** [comment]
Need to add a table of config settings similar to http://loopback.io/doc/en/lb3/MySQL-connector.html#properties

**Comment by smartmouse** [comment]
@benkroeger : Thank you for the information. 
May I confirm with you,  url is a string.
By setting url to false, do you mean just remove it from the json?
I would like to be accurate when we update the information.
Thank you in advance for your help.

datasources.production.json
{
  "myDS": {
    "host": "localhost",
    "port": 27017,
    "url": "",
    "database": "test",
    "password": "mypassword",
    "name": "myDS",
    "user": "me",
    "connector": "mongodb"
  }

**Comment by benkroeger** [comment]
[the code](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L71) only tests for `url` to be *truthy*, so anything *falsy* (`null`, `false`, ` `...) would do. **Except** for `undefined`, since that would mean to not overwrite the value from the general `datasources.json` file (==> when `datasources.production.json` gets merged with `datasources.json`, `undefined` values from `datasources.production.json` are ignored!)

That said, removing `url` from the json does not solve the problem and would be wrong in the documentation.

**Comment by smartmouse** [comment]
Thanks for the clarification :-)

**Comment by ritch** [comment]
Hey @smartmouse are you looking into this issue?

**Comment by smartmouse** [comment]
yes, I am trying to enhance our document.

**Comment by crandmck** [comment]
I believe this has been addressed with c07afe79dc3ac1803ee4119cff0e238aa5ee72f3.
However, it doesn't mention setting `url` to `false`.  @smartmouse do we need to mention that?
Otherwise, I think we can close this.

**Comment by smartmouse** [comment]
@rand, we have not document this. This usage is basically using url in the datasource.json globally  while using a specific  datasource.production.json  that does not use url but uses the indivdual connection parameters .  It is important to tell people how and also important to mention  that removing the url entry will not override the behaviour as suggested.

=== These are reworded  from @benkroeger  's information ===
If LGTM, we can add one paragraph to it.  Thanks

If you use url  in  datasource.json  as a global setting  that will ignore all the connection parameter e.g.host, user, password, port  but  want to override the datasource.json with a specific environment  e.g. datasource.production.json and use the connection parameters - host, user, password instead of a single url.

In the special environment datasource.production.json

You must set the url to be false, null or “”.
If you set url to undefined or remove the url , the override will not work.

**Comment by crandmck** [comment]
OK so @smartmouse can you add this to the doc?

**Comment by smartmouse** [comment]
@crandmck working on it. Thanks

**Comment by smartmouse** [comment]
The changes has been merged with @crandmck 's blessings and help :+1:
