### ISSUE TITLE
Upgrade to the latest mongodb driver 2.1.16

### ISSUE THREAD

**Issue by demsey2** [strongloop/loopback-connector-mongodb#242]
I have a few issues with connection to mongodb database. After sometime my API stopped working and displays "topology was destroyed". I looked at similar issues with other nodejs frameworks and libraries and most of them point to some issues with connection. It has been fixed but "loopback-connector-mongodb" has a dependency to the old mongodb driver which also points to the old mongodb-core module.

Is there any plan to upgrade that or I can start looking at other dbs?

In case someone is wondering this is my setup
- AWS EBS Instance running loopback 2.27.0
- MongoDB 3.0 with mlab.com

**Comment by Amir-61** [comment]
Please see [here](https://github.com/strongloop/loopback-connector-mongodb/pull/244#issuecomment-218712429); this is a bug in the `mongodb` module. The peer dependency is listed by `mongodb-core`, which is a dependency of `mongodb`.

Please folow the issue here: https://jira.mongodb.org/browse/NODE-612

Closing now...
Thanks!
