### ISSUE TITLE
"near" filter (version 2.53.0) crashes the server if used with an empty current position object.

### ISSUE THREAD

**Issue by youngtt** [strongloop/loopback-connector-mongodb#290]
Filtering on GeoPoint property within an embedded model always return empty [] results:

`where: { 'geoList.point' : { near: { lat: 0, lng: 0} } }`
- 'geoList' being property name of an embedsOne/embedsMany model
- 'point' being a GeoPoint property in the embedded model

**Comment by betonildo** [comment]
No fix yet?

**Comment by youngtt** [comment]
Nope.

Used the latest GitHub build for both loopback-connector and connector-mongodb

**Comment by jannyHou** [comment]
@youngtt @betonildo 
I am trying to reproduce the issue.
Could you fork https://github.com/strongloop/loopback-sandbox and replace with your code?
Thanks!


This is probably raised due to same bug in https://github.com/strongloop/loopback-connector-mongodb/issues/285

**Comment by Amir-61** [comment]
Is this still an issue?

**Comment by Zvika88** [comment]
I've been working with juggler 2.49 since the bug report and for most cases
it was OK. I'll try the new version over the next few days and let you
know. Thanks!

**Comment by youngtt** [comment]
Hi Amirali,

From my tests, the issue is still present.  Here’s my fork with the test cases:  https://github.com/youngtt/loopback-sandbox

Cheers.

- Young

**Comment by jannyHou** [comment]
@youngtt Thank you for the sandbox. 
I believe it's the same issue with https://github.com/strongloop/loopback/issues/517
The problem is at this moment we don't support "Filter on level 2 properties", so when you filter against `sub.geo` like
```
where: {
	'sub.geo' : { 
		near: aPoint,
		maxDistance: 1,
		unit: 'kilometers'
	}
}
```
it fails to get the result.

And another thing not related to the bug but need to correct here:
The embedded instance should be created independently, otherwise it's only a property in parent instance, won't be stored in db.
Eg: After you create `Main` instances in https://github.com/youngtt/loopback-sandbox/blob/master/server/boot/createData.js#L7-L23, you will not find `Sub` instances by `Sub.find()`.

Details please see our doc: http://loopback.io/doc/en/lb2/Embedded-models-and-relations.html#embedsmany, it's explained in note "Important"

**Comment by youngtt** [comment]
Noted.   You aware of any fix in the works for this?

**Comment by jannyHou** [comment]
@youngtt "Filter on second level properties" has the most thumbs up from community and I believe we will work on supporting that in the near future.

To keep git clean for features&bugs I am closing this issue. We can move further discussion under https://github.com/strongloop/loopback/issues/517
Thanks for understanding.

**Comment by Zvika88** [comment]
major issue: "near" filter (version 2.53.0) crashes the server if used with an empty current position object.

**Comment by betonildo** [comment]
Hi, i made the fix at
https://github.com/betonildo/loopback-connector-mongodb.git

Just reference the package as git Repo with tag 1.15.8

"git+ https://github.com/betonildo/loopback-connector-mongodb.git#1.15.8"

Fixes of my fix are welcome!

Thanks
Em 27/10/2016 13:47, "youngtt" <notifications@github.com> escreveu:

> Noted. You aware of any fix in the works for this?
>
>

**Comment by jannyHou** [comment]
@betonildo @Zvika88 Thanks for contribution and feedback. I changed this issue title to ""near" filter (version 2.53.0) crashes the server if used with an empty current position object."

And @betonildo could you send a pull request against `loopback-connector-mongodb`? I will take a look and merge it if it fixes the bug. You can follow our doc to see how to create pr: http://loopback.io/doc/en/contrib/code-contrib.html#where-to-start
Thanks!
