### ISSUE TITLE
Publish new major version 

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-connector-mongodb#308]
Now we only have one major version as loopback-connector-mongodb@1.x but the latest release(1.17.0) is not compatible with juggler3.x

Suggestion here is we need two major versions in mongodb:
  - version 1.x: compatible with juggler@2.x
    - code in branch "loopback-2.x"(confirmed compatible with juggler@2.x)
  - version 2.x: compatible with juggler@3.x
    - code in branch master(confirmed compatible with juggler@3.x)

cc @strongloop/fa-db-connectors @bajtos

**Comment by bajtos** [comment]
> Now we only have one major version as loopback-connector-mongodb@1.x but the latest release(1.17.0) is not compatible with juggler3.x

How comes? I don't remember making any intentional changes that would make the mongodb connector behave differently on LB 2.x vs 3.x

> Suggestion here is we need two major versions in mongodb:

I strongly prefer to have a single version that supports both 2.x and 3.x versions of LoopBack, so that we have less major versions to maintain. Unless the effort needed to support two LoopBack versions outweighs the maintenance costs.

> version 1.x: compatible with juggler@2.x
> code in branch "loopback-2.x"(confirmed compatible with juggler@2.x)

No. The rule is to use a branch called `N.x` to track source code of a semver-major released `N.a.b` (for any `a` and `b`). In this particular case, version `1.x` would live in a branch called `1.x`.

The branch `loopback-2.x` is to run CI builds of `master` with `loopback@2` as a dev-dependency. If master no longer supports loopback 2.x, then the branch `loopback-2.x` can be deleted.

Note that we are already working on a new major release as part of dropping support for Node v0.10/v0.12, see https://github.com/strongloop/loopback-connector-mongodb/pull/309

**Comment by jannyHou** [comment]
@bajtos Hmm, I should add more context in this issue:
Some users observe failure with latest release version `loopback-connector-mongodb@1.17.0`, see issue https://github.com/strongloop/loopback-connector-mongodb/issues/296, and comment https://github.com/strongloop/loopback-connector-mongodb/issues/296#issuecomment-261583363 says it might be a compatibility problem.

I run `npm test` of `loopback-connector-mongodb@1.17.0` with `juggler@2.53.0` and saw 10+ failures, then I opened this issue, but after the first run I could not see those errors again. 

I am closing this issue now because it's based on a unreproducible assumption :(
