### ISSUE TITLE
query with near & order filters doesn't work together

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-connector-mongodb#310]
The original issue opened in loopback: https://github.com/strongloop/loopback/issues/2917
And turns out it is a mongodb specific issue.

I reproduced it in `loopback-connector-mongodb` with test case https://github.com/strongloop/loopback-connector-mongodb/blob/07afdbfa02476d04bcc08b1cb7008d622987a51b/test/mongodb.test.js#L1527

filter:
```js
order: '_id DESC',
where: {
       location: {
       near: new GeoPoint(coords),
       maxDistance: 17000,
       unit: 'meters',
      },
},
```

and result are not ordered by `_id`

**Comment by jannyHou** [comment]
cc @TuNi54 @balanza

**Comment by TuNi54** [comment]
Hi,

Can someone help ?

Thanks

**Comment by balanza** [comment]
I can fix it, but I need to understand what is the behaviour we want to achieve. I propose this:

```
IF has {near} without {maxDistance} THEN
   don't sort at all /* mongodb itself will order by a distance criterium */
IF not has {near} OR has {near} with {maxDistance} THEN
   sort by {sorting} parameters /* and scale to {_id} id {sorting} undefined, as it is now */
```

@jannyHou do you agree with this algorithm?

**Comment by TuNi54** [comment]
@jannyHou  can I confirm the previous message pls ? 
Thank you

**Comment by jannyHou** [comment]
Now the question seems to be:
If we have both `order` and `near` to sort the result, which one has higher priority?
And if `near` includes `maxDistance`, will it affect the priority?

@raymondfeng @ritch @superkhau @bajtos Any thoughts? Thanks.

**Comment by superkhau** [comment]
@jannyHou IMO, it depends on how the query is structured and the nesting level of each operation. Inside out is the way I see it.

**Comment by bajtos** [comment]
> If we have both `order` and `near` to sort the result, which one has higher priority?

In my opinion, `order` has higher priority than `near`.

> And if near includes maxDistance, will it affect the priority?

As I see it, it should not affect the priority - explicit `order` has always the highest priority.

---

I would argue that if the user has provided `filter.order` value, then we should either honour it (when there is a way how to get the requested results) or return a `400 Bad Request` error if we (or the database) cannot fulfil such query (e.g. because we cannot load all results into memory to sort them, this typically happens when using `order` with `limit`/`skip`).

When looking at the query posted in the original loopback bug:

```js
{
                order : "date desc",
                limit : 10,
                skip : 0,
                where : {
                    found : "false",
                    coords : {
                        near : [lat, lng], 
                        maxDistance : 50000, 
                        unit : 'meters'
                    },
}
```

The client wants the newest 10 results that are within given `maxDistance`. To achieve this, we have to either
 1. Ask MongoDB to sort it using `date` and return only the first 10 results, assuming MongoDB does support such query.
 2. Fetch *all* records within `maxDistance`, sort them in memory and then return only the first 10 items.

**Comment by superkhau** [comment]
@bajtos Good points, one thing I'm curious about though. Is it the ORM's job to support sort for an underlying DB that doesn't support it? If the DB can't sort all those records, why should we sort in memory what the DB (which was probably optimized for this type of operation) can't do? I can see a speed argument for in mem, but maybe we can allow the user to do a custom query for those edge cases?

**Comment by bajtos** [comment]
> Is it the ORM's job to support sort for an underlying DB that doesn't support it?

I think that's a decision each ORM need to make.

> If the DB can't sort all those records, why should we sort in memory what the DB (which was probably optimized for this type of operation) can't do? I can see a speed argument for in mem, but maybe we can allow the user to do a custom query for those edge cases? It is a nice to have though. ;)

If we want allow users to easily switch between databases without code/client changes, then we need to support a reasonable subset of geopoint operations for all connectors. So that an app written for MongoDB can be switched to let's say MySQL while preserving the client API.

To be honest, I think that idea sounds better in theory than it turns out in practice. For example, just today I came across a StackOverflow [question](http://stackoverflow.com/q/41105914/69868) where the person has 150k records in the database and a simple geopoint query requires about a second to run, utilizing 100% CPU during that time.

In that light, I am leaning towards the following:

*If the user has provided `filter.order` value, then we should either honour it (when there is a way how build a database query to get the requested results) or return a `400 Bad Request` error if the database cannot fulfil such query.*

**Comment by superkhau** [comment]
>I think that's a decision each ORM need to make.

I agree, the question is do we? I'm leaning more towards supporting the operations provided by the DB and allow the user to string up the operations to do those things.

>...To be honest, I think that idea sounds better in theory than it turns out in practice.

In your example, say MongoDB supports a type of Geopoint op and MySQL does, as long as they have the same API in Juggler, all is well. Now let's say MySQL does not support the op, do we go as far as crafting up some custom solution to make MySQL support it? IMO, no. I say just tell the user MySQL doesn't support and to use a custom query THEY can research using the MySQL docs. Otherwise, we'll end up supporting every permutation/combination of all supported and future connectors (or a subset that will grow into asking for more permutations/combinations).

>If the user has provided filter.order value, then we should either honour it (when there is a way how build a database query to get the requested results) or return a 400 Bad Request error if the database cannot fulfil such query.

I think this is good except the "a way to build a database query" part which is gray. I would say "when there is a way provided OOB by the underlying DB to get the requested result". So we don't get into the game of crafting up custom solutions mentioned above (and prevent all the edge cases like fetch all in-mem", which may not all fit, and all that baggage).

**Comment by bajtos** [comment]
> I think this is good except the "a way to build a database query" part which is gray. I would say "when there is a way provided OOB by the underlying DB to get the requested result".  So we don't get into the game of crafting up custom solutions mentioned above (and prevent all the edge cases like fetch all in-mem -- which may not fit in mem -- and all that baggage that comes along with it).

Let's start with returning 400 Bad Request if there isn't any easy solution we would know. If somebody from our community contributes a decent implementation, then I think we should accept it into the connector.

**Comment by TuNi54** [comment]
Hi,

Can someone do the change please? 

Thanks !

**Comment by bajtos** [comment]
So according to [MongoDB docs](https://docs.mongodb.com/manual/reference/operator/query/near/#sort-operation), the database does support `near` queries with custom sorting rules.

> $near sorts documents by distance. If you also include a sort() for the query, sort() re-orders the matching documents, effectively overriding the sort operation already performed by $near. When using sort() with geospatial queries, consider using $geoWithin operator, which does not sort documents, instead of $near.

So the question is how to modify loopback-datasource-juggler and loopback-connector-mongodb to use `$geoWithin` + `sort` in this particular case.

@TuNi54 as a temporary workaround, you can write a custom [remote method](http://loopback.io/doc/en/lb3/Remote-methods.html) that will query MongoDB directly. Something along the following lines (I didn't run the code myself, it will probably not work out of the box):

```js
// common/location.js
module.exports = function(Location) {
  Location.findMostRecent = function(cb) {
    var self = this;
    var query = { /* MongoDB query you want to run */ };
    self.dataSource.connector.execute(self.modelName, 'find', query, function(err, data) {
      data = self.fromDatabase(model, data);
      cb(err, data);
    });
  };

  Location.remoteMethod('findMostRecent', {
    returns: { arg: 'data', type: [Location], root: true },
    http: { verb: 'get', path: '/recent' },
  });
};
```

**Comment by jonathan-casarrubias** [comment]
Hi @bajtos good to see you again,

Hey so, this is a great topic, I also I'm glad you brought to the table the big collections issue.

I have a customer right now with a geolocation based application, just for giving some context, we are importing lifestyle establishments from social sources, I mean restaurants, bars, tavernas, etc.

We are parsing entire areas (cities) and right now we have more than 30k venues imported, but that is just the beginning we have a reduced amount of areas.

There are 2 problems though

1.- We need to order by popularity, as you all know we can not order and search using nearby right now, si it basically returns whatever is closer, but that is not the expected behaviour..  As you said, explicit order operator should be priority, so I would like to get more popular venues, even if these are a little far away from other closer non-popular places.

2.- The query is starting to get super slow, it uses a huge amount of resources just to get 5 places around, about 5 seconds to return, so I tried to implement a mongodb 2dsphere index for this query, but I can not because the LoopBack GeoPoint is stored in {lat, lng} but the mongodb Point type is actually different, something like { type: 'Point', coordinates: [lng, lat]}

so right now we have these 2 critical issues that won't allow us to address our customer requirements.

Also as you said I'm thinking in doing a remote method for this, but I need to bring this to the table so you know that complex applications based on geolocation, will depend in the ability of ordering and provide a good performance, mainly by indexing the right Point type.

Thoughts?

Cheers
Jon

**Comment by bajtos** [comment]
@jonathan-casarrubias hey, it's great to hear from you too! I always love to see how people are using LoopBack in real world apps.

I feel your pain regarding the current status of geolocation support in MongoDB connector (and possibly in LoopBack in general).

I am afraid fixing this issue is not a priority for us right now, however if you can contribute the necessary improvements yourself, then we are happy to help you along the way! See http://loopback.io/doc/en/contrib/code-contrib.html to get started.

> 1.- We need to order by popularity, as you all know we can not order and search using nearby right now, it basically returns whatever is closer, but that is not the expected behaviour.. As you said, explicit order operator should be priority, so I would like to get more popular venues, even if these are a little far away from other closer non-popular places, that with a combination of maxDistance we would like to get the 20 more popular places either around new york or a user device for instance.

I am not very familiar with this codebase, but I would hope this should be a relatively straightforward change in how juggler and/or MongoDB connector builds the query passed down to MongoDB driver.

> The query is starting to get super slow and consume tons of memory on the dedicated LoopBack Server, it uses a huge amount of resources just to get 5 places around, about 5 seconds to return, so I tried to implement a mongodb 2dsphere index for this query, but I can not because the LoopBack GeoPoint is stored in {lat, lng} but the mongodb Point type is actually different, something like { type: 'Point', coordinates: [lng, lat]}

The tricky part here is how to preserve backwards compatibility for existing applications that already have data stored in the current `{lat, lng}` format. I think we should introduce model-level and/or datasource-level setting to control the geopoint format and allow LoopBack users to opt into the new (fixed) behaviour.

cc @ritch @raymondfeng @superkhau

**Comment by jonathan-casarrubias** [comment]
@bajtos  sure I can do that,

For now I'm in a rush to deliver this project, but once I get more experienced with the entire geolocation context I will allocate some time to work on this.

Cheers
Jon

**Comment by fbalabanov** [comment]
I am getting this issue.
still not resolve?

**Comment by bajtos** [comment]
@fbalabanov Hello, I am afraid we don't have bandwidth to solve all issues our users are reporting, and this one has not been a high priority for us so far. Especially considering there is a workaround available (see https://github.com/strongloop/loopback-connector-mongodb/issues/310#issuecomment-270367248). Does the workaround work for you?

If you are willing to invest the time to fix this issue, then we are happy to help you along the way. See http://loopback.io/doc/en/contrib/code-contrib.html to get you started, possibly also https://www.nearform.com/blog/first-time-with-open-source/ if you are new to GitHub.

**Comment by fbalabanov** [comment]
Thank your kindly.
https://github.com/strongloop/loopback-connector-mongodb/issues/310#issuecomment-270367248

**Comment by fbalabanov** [comment]
that is not working for me.

**Comment by fbalabanov** [comment]
you want me to fix this issue?

**Comment by bajtos** [comment]
> you want me to fix this issue?

Yes please, if you can and want to!
