### ISSUE TITLE
Rapid Increase in Connections Causes Severe Performance Degradation.

### ISSUE THREAD

**Issue by vickoman** [strongloop/loopback-connector-mongodb#456]
In spite of having a Pool Connection configured, we observed a rapid increase in our connections to mongodb and we still do not have much concurrence.

We have seen that is a bug in native mongodb and was fixed in Aug 02 2018 in the 3.1.3 version, this is a critical fix for ours production enviroments. for now we have to restart our mongo cluster every two days.

FIX REFERENCE:
https://jira.mongodb.org/browse/NODE-1595

**Comment by dhmlau** [comment]
@strongloop/sq-lb-apex ^^

**Comment by virkt25** [comment]
`"mongodb": "^3.0.1",` -- mongodb is marked with a `^`, meaning that we should automatically pick up the latest version of the mongodb fix. Can you re-deploy the application so that the latest dependencies are installed. (Updated`package-lock.json` if it exists). Ensure you are using `loopback-connector-mongodb` `^3.0.0`. For reference the latest is `3.6.0`.
