### ISSUE TITLE
MongoError: unknown operator: $$eq

### ISSUE THREAD

**Issue by zekylaf** [strongloop/loopback-connector-mongodb#532]
Hi, I was using **v3.9.2** and it was working good. Recently I updated to **v5.0.0** and I am getting this error when trying to use $eq operator.

`MongoError: unknown operator: $$eq`

I am using `allowExtendedOperators: true`.

The way I am using it: 

```
var args = {
  where: {
    title: {
      "$eq": {
        name: "book name",
        description: "book description"
      }
    }
  }
}

Book.find(args, function(err, res){
  ...
});
```

Something I can do?
Thanks

## Acceptance Criteria

- [x] Investigate and find the cause
- [x] add explanations and examples to the mongodb connector dosc
- [x] remove `pushAll` from [the list](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L752) as it is deprecated. 
- [x] MongoDB operations have the prefix $. Even the LB4 supported operations don't need the `$`, Mongodb users might tend to add the prefix. This issue might be caused by removing the step to clean$ in the buildWhere. Maybe we can add it back.
- [x] Update tests to include the bug caught

**Comment by dhmlau** [comment]
@hacksparrow , could you please take a look? Thanks.

**Comment by hacksparrow** [comment]
@zekylaf can you share a sample app reproducing the error? I checked on a LB3 app, I don't get that error.

**Comment by zekylaf** [comment]
Sure. https://github.com/zekylaf/lb-eq-test

Run it with:
npm install
npm run testeq

Thanks

**Comment by hacksparrow** [comment]
Thanks @zekylaf

**Comment by hacksparrow** [comment]
@zekylaf please use this workaround while we work on a solution:

```js
  var args = {
    where: {
      'title.name': 'book name',
      'title.description': 'book description',
    }
  };
```

**Comment by zekylaf** [comment]
@hacksparrow great, thanks.

**Comment by fhsakai** [comment]
Dear @hacksparrow,
That issue is closed, but is there any plan to correct it?
Should I open a new one?
To allow to use the mongoDB operator without duplicate the $

until the release v3.9.2 we have in the buildWhere a step to clean $ from the operator before the handler
if (spec.charAt(0) === '$') spec = spec.substr(1);  ( v3.9.2)
but it's since v4.0.0

**Comment by hacksparrow** [comment]
Re-opened. @fhsakai

**Comment by dhmlau** [comment]
@agnes512, could you please take a look at this? Thanks.

**Comment by deeeed** [comment]
This error is applicable to all operators "$lt" "$gte" etc... Please fix.

**Comment by agnes512** [comment]
For everyone who's watching is issue:
- for MongoDB supported **update operators**:
  - `$currentDate`, `$inc`, `$max`, `$min`, `$mul`, `$rename`, `$setOnInsert`, `$set`, `$unset`
  - `$addToSet`, `$pop`, `$pullAll`, `$pull`, `$push`
  - `$bit`
They work with `"^5.0.0"` as well. To enable these operators, please indicate `allowExtendedOperators: true` in your `datasource` configuration or the model definition. ( up to what scope you'd like to have)

- for other query operators, such as `eq` `lt` `and`, etc:
Please check out the [`Where` filter](https://loopback.io/doc/en/lb4/Where-filter.html#operators) docs. It lists all the operators that LB supports and example usages. 

And here are some examples for using the MongoDB update operators:

- Update the price for all the products if their current price is lower than 100:
  - For LB4 users:
```
 await productRepo.updateAll({ $max: { price: 100 }}, {// where clause goes in here});
```
you might need to do some type conversion to make Typescript happy:
```
 await customerRepo.updateAll({ $max: { num: 100 } } as unknown as Product);
```
  - For LB3 users:

```
Product.updateAll(
            {// where clause goes in here},
            {$max: {price: 100}},
            options,
            function(err, updateproducts) {
           ...
```

I think there are two things to imrove: 
- add these to the mongodb connector dosc
- MongoDB operations have the prefix `$`. Even the LB4 supported operations don't need the `$`, Mongodb users might tend to add the prefix. This issue might be caused by removing the step to clean`$` in the buildWhere as @fhsakai suggested. Maybe we can add it back.
