### ISSUE TITLE
fields filter can not be used if mongoDB model defines columnName/fieldName

### ISSUE THREAD

**Issue by apparentvisuals** [strongloop/loopback-connector-mongodb#570]
## Steps to reproduce

1. Using MongoDB connector defined a model with a property such as:
```
@property({ type: string, mongodb: { columnName: a_value }})
aValue: string
```
2. Find using filter { fields: { aValue: true }}

## Current Behavior

when using filter.fields.aValue = true the result is missing

## Expected Behavior

should return the value

## Link to reproduction sandbox

No re-production sandbox however the bug is in loopback-connector-mongodb/lib/mongodb.js line 1270
```
// this call expect data to be an object but data is an array when coming from a find query
MongoDB.prototype.convertColumnNames = function(model, data, direction)
```

If you agree the issue is here then I am happy to submit a merge request as I need this to work. Otherwise please recommend the best place to apply the fix.

## Additional information
```
├── @loopback/authentication@4.2.1
├── @loopback/boot@2.1.1
├── @loopback/context@3.5.1
├── @loopback/core@2.4.1
├── @loopback/openapi-v3@3.2.1
├── @loopback/repository@2.2.1
├── @loopback/rest@3.3.1
├── @loopback/rest-explorer@2.1.1
├── @loopback/service-proxy@2.1.1
├── loopback-connector-mongodb@5.2.3
```

**Comment by agnes512** [comment]
@apparentvisuals I reproduced it. Thanks for reporting the bug. I also checked MySQL, seems like the issue only exists in Mongo connector. I will do some investigation.

**Comment by mitsos1os** [comment]
@agnes512 if you don't mind I can help since I have worked on this code!
@apparentvisuals you are right. You are right about the function taking as input an array when expecting an object.

I would also advise you to look at the preparation of the inputs for this function [here](https://github.com/strongloop/loopback-connector-mongodb/blob/6c946d1278dbc4b0ea106127bbe793997157d46d/lib/mongodb.js#L1356) :smile: 

I can help with the PR if you need anything

**Comment by apparentvisuals** [comment]
@mitsos1os I figured there were path where this function does indeed receive an object, which I see in fromDatabase does so as the data from mongo is an object. 

My quick fix was to allow both input types and perform an array check on the data input inside the function and produce the right output accordingly. This fixed the problem and didn't break any query behaviour.

@agnes512 I wasn't sure if this is the type of fix you are planning or something more consistent. I can always put up the change as a PR if needed.

**Comment by mitsos1os** [comment]
@apparentvisuals No matter what since this is a bug, I believe it would be cool if you submitted a PR to fix it!

As for the approach I believe `convertColumnNames` should keep receiving objects. You should make sure it does so by converting the data before it gets passed into it. In our case this is already done a couple lines below where I pointed out, so I would suggest the change to go there.

If you are willing to submit the PR, we can continue the discussion there if you would like

**Comment by agnes512** [comment]
@apparentvisuals @mitsos1os thank you two! And yes I think it's something related to the type, but I haven't taken a closer look at it yet. It'd be good to see a PR. I'd love to review it 👍

**Comment by jetstudio-io** [comment]
hi @agnes512, I fixed this bug & create the PR. Can you make the review pls?

**Comment by agnes512** [comment]
Thank @jetstudio-io for fixing it in #625 !
