### ISSUE TITLE
how could I use MongoDB.prototype.buildWhere() function?

### ISSUE THREAD

**Issue by makersu** [strongloop/loopback-connector-mongodb#74]
I'd like to use aggregate but I have to convert queries like { "upload_time": {"gt": "2014-12-01T00:00:00.000Z"}} to { "upload_time": {$gt: new Date("2014-12-01T00:00:00.000Z")} for $match.
I found MongoDB.prototype.buildWhere function, how could I use it?
Thank you very much.

```
//json
{
    "acn":"jason",
    "email":"jason@gmail.com",
    "where": {
        "and": [
            { "upload_time": {"gt": "2014-12-01T00:00:00.000Z"}}
        ]
    }
}
//numessage.js
var numessageCollection = Numessage.getDataSource().connector.collection(Numessage.modelName);
numessageCollection.aggregate([
                {$match: { $and:[ { key: { $in: siteIds } }, { "upload_time": {$gt: new Date("2014-12-01T00:00:00.000Z")}} ] } },
                {$group: { _id: {owner:"$owner"}, total: { $sum: 1 } } }
          ], function(err, groupByRecords) {
                ...
            });
```

**Comment by dcajio** [comment]
This has gone unanswered for close to a year now.  Has there been any traction on this, another way to handle it, or is it still not possible?

**Comment by lkappeler** [comment]
I came across this Issue because we have Implemented a custom find method with aggregations for a customer project which had the same Issue with the date conversion.

In general this a problem which should not be handled by a specific connector implementation, because it makes no sense in terms of architecture. ( eg every connector would have to implement it. Which could lead in to some strange behaviours when switching the data source.)

The problematic is already handled in the [loopback-datasource-juggler]( https://github.com/strongloop/loopback-datasource-juggler) package.
The datasource-juggler implements a Method called [normalize](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L1477) which then passes the where part of the given filter to the [coerce](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L1628) function. This function coerce values based on the property types.

Normally the JSON (eg. query filter) comes from the request and passes this function before being passed to the database specific connector. If this is not the case eg overriding the find function as mentioned in the introduction, you have to pass your filter manually to the normalize function. The given result will then be converted as defined in the model and can be used for the further processing.

**Comment by ssh24** [comment]
What @lkappeler said is correct. Juggler calls a function when a query is passed for a `find` operation to normalize the query and get rid of unnecessary properties from the query. You can use `find` directly with a filter that you would like to use or make sure whatever filter you choose is normalized before calling the `buildWhere` function itself.

Hopefully this answered the question for this issue. Closing this as a result. Feel free to reopen if needed.
